services:
  redis:
      image: 'redis:7-alpine'

  app:
    image: 'mafuba1/cloud-file-storage'
    ports:
      - '8080:8080'
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: 'postgres:16-alpine'
    restart: always
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  minio:
    image: 'minio/minio'
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data_prod:/minio
    command: server /minio

volumes:
  db_data_prod:
  minio_data_prod:
